### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by MartinBraquet** [blegat/git-dot#3]
I try to install it but I get
```
$ sudo python setup.py install
error in smartcp setup command: ("EntryPoint must be in 'name=module:attrs [extras]' format", 'git-dot=git-dot:main')
```
Do you know how to fix it?

**Comment by blegat** [comment]
Does #4 fixes the issue ?

**Comment by MartinBraquet** [comment]
Yes, but I'm facing an import error:
```
$ git-dot -h
Traceback (most recent call last):
  File "/usr/local/bin/git-dot", line 11, in <module>
    load_entry_point('git-dot==0.1', 'console_scripts', 'git-dot')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named git_dot
```
Which command have I to encode to produce the .dot file?
Just `git-dot graph.dot`?

**Comment by blegat** [comment]
Yes :)
Does it work now ? I have just updated the PR #4

**Comment by MartinBraquet** [comment]
Yes, alright ! Is it possible to generate a small part of the graph?

**Comment by blegat** [comment]
Not currently no but it would be a nice feature to add
